"""
Learner Profile and Prediction API Endpoints.
"""

from typing import List, Dict, Any
from fastapi import APIRouter, Depends, HTTPException, status
from src.api.schemas import LearnerProfileResponse, PredictRequest, PredictResponse
from src.api.dependencies import get_artifact_store, ArtifactStore

router = APIRouter(prefix="/api/learners", tags=["Learners"])


@router.get("", response_model=List[Dict[str, Any]])
def list_learners(store: ArtifactStore = Depends(get_artifact_store)):
    """
    Lists summary metadata for all 1,000 available learner profiles.
    
    Returns:
        List of learner summary objects containing ID, skill level, risk status, and performance score.
    """
    summary_list = []
    for lid, prof in store.profiles.items():
        summary_list.append({
            "learner_id": lid,
            "skill_level": prof.get("skill_level", "Intermediate"),
            "performance_band": prof.get("performance_band", "Moderate"),
            "risk_status": prof.get("risk_status", "Low Risk"),
            "predicted_performance": prof.get("predicted_performance", 0.0)
        })
    # Sort by learner ID
    summary_list.sort(key=lambda x: x["learner_id"])
    return summary_list


@router.get("/{learner_id}/profile", response_model=LearnerProfileResponse)
def get_learner_profile(
    learner_id: str,
    store: ArtifactStore = Depends(get_artifact_store)
):
    """
    Retrieves the structured learner intelligence profile generated by Phase 3.
    
    Args:
        learner_id: Target learner ID (e.g. LEARNER_0001 or L0001).
        
    Returns:
        LearnerProfileResponse containing performance bands, risk status, topic mastery, and personalization flags.
        
    Raises:
        HTTPException 404: If learner ID does not exist in profiles dataset.
    """
    profile = store.get_profile(learner_id)
    if not profile:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Learner profile for '{learner_id}' not found."
        )
    return profile


@router.post("/predict", response_model=PredictResponse)
def predict_learner_performance(
    payload: PredictRequest,
    store: ArtifactStore = Depends(get_artifact_store)
):
    """
    Optional prediction endpoint executing Phase 2 ML models on raw telemetry.
    
    Args:
        payload: PredictRequest containing 18 raw telemetry features.
        
    Returns:
        PredictResponse containing predicted performance score, risk status, and skill level.
    """
    if not store.models_loaded:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Phase 2 ML models are unavailable."
        )
    try:
        data_dict = payload.model_dump() if hasattr(payload, "model_dump") else payload.dict()
        return store.predict_telemetry(data_dict)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Prediction failed: {str(e)}"
        )
