"""
Personalized Recommendation API Endpoints.
"""

from fastapi import APIRouter, Depends, HTTPException, status
from src.api.schemas import RecommendationResponse
from src.api.dependencies import get_artifact_store, ArtifactStore

router = APIRouter(prefix="/api/learners", tags=["Recommendations"])


@router.get("/{learner_id}/recommendations", response_model=RecommendationResponse)
def get_learner_recommendations(
    learner_id: str,
    store: ArtifactStore = Depends(get_artifact_store)
):
    """
    Retrieves ranked, deterministic personalized learning recommendations generated by Phase 4.
    
    Args:
        learner_id: Target learner ID (e.g. LEARNER_0001 or L0001).
        
    Returns:
        RecommendationResponse object containing ranked recommendations list and next_best_action.
        
    Raises:
        HTTPException 404: If learner ID does not exist in recommendations dataset.
    """
    rec_result = store.get_recommendation(learner_id)
    if not rec_result:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Recommendations for '{learner_id}' not found."
        )
    return rec_result

